### CRISP-DM Phase 2: Data Understanding

**Data Source:** Yahoo! Finance API (https://github.com/ranaroussi/yfinance) for market data

**Task Type:** Binary Classfication

In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

Pulling 5 years of open and close prices of the Magnificent 7 Stocks in US Stock Market.

In [41]:
tickers = ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "NVDA", "TSLA"]
start_date = "2021-01-01"
end_date = "2026-01-01"
open_close_data = yf.download(tickers, start=start_date, end=end_date)
open_close_data

C:\Users\WEN YUAN\AppData\Local\Temp\ipykernel_2992\4122296919.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  open_close_data = yf.download(tickers, start=start_date, end=end_date)
[*********************100%***********************]  7 of 7 completed

Price            Close                                                  \
Ticker            AAPL        AMZN       GOOGL        META        MSFT
Date
2021-01-04  125.974457  159.331497   85.659286  267.074402  208.882248
2021-01-05  127.531960  160.925507   86.350060  269.090332  209.083679
2021-01-06  123.239052  156.919006   85.497993  261.483490  203.662308
2021-01-07  127.444389  158.108002   88.051697  266.875793  209.457962
2021-01-08  128.544388  159.134995   89.217392  265.713898  210.734100
...                ...         ...         ...         ...         ...
2025-12-24  273.809998  232.380005  314.089996  667.549988  488.019989
2025-12-26  273.399994  232.520004  313.510010  663.289978  487.709991
2025-12-29  273.760010  232.070007  313.559998  658.690002  487.100006
2025-12-30  273.079987  232.529999  313.850006  665.950012  487.480011
2025-12-31  271.859985  230.820007  313.000000  660.090027  483.619995

Price                                     High                          ...  \
Ticker            NVDA        TSLA        AAPL        AMZN       GOOGL  ...
Date                                                                    ...
2021-01-04   13.076726  243.256668  130.062953  163.600006   87.463646  ...
2021-01-05   13.367160  245.036667  128.242590  161.169006   86.686514  ...
2021-01-06   12.579125  251.993332  127.570919  159.875504   86.544590  ...
2021-01-07   13.306581  272.013336  128.135547  160.427002   88.224388  ...
2021-01-08   13.239514  293.339996  129.108992  159.531998   89.293318  ...
...                ...         ...         ...         ...         ...  ...
2025-12-24  188.610001  485.399994  275.429993  232.949997  315.079987  ...
2025-12-26  190.529999  475.190002  275.369995  232.990005  315.089996  ...
2025-12-29  188.220001  459.640015  274.359985  232.600006  314.019989  ...
2025-12-30  187.539993  454.429993  274.079987  232.770004  316.950012  ...
2025-12-31  186.500000  449.720001  273.679993  232.990005  314.579987  ...

Price             Open                             Volume                      \
Ticker            MSFT        NVDA        TSLA       AAPL      AMZN     GOOGL
Date
2021-01-04  213.526418   13.067502  239.820007  143301900  88228000  37324000
2021-01-05  208.469574   13.063015  241.220001   97664900  53110000  20360000
2021-01-06  203.585543   13.185420  252.830002  155088000  87896000  46588000
2021-01-07  205.379917   12.931136  259.209991  109578200  70290000  41936000
2021-01-08  209.832131   13.325024  285.333344  105158200  70754000  35484000
...                ...         ...         ...        ...       ...       ...
2025-12-24  485.679993  187.940002  488.480011   17910600  11420500  10097400
2025-12-26  486.709991  189.919998  485.230011   21521800  15994700  10899000
2025-12-29  484.859985  187.710007  469.000000   23715200  19797900  19621800
2025-12-30  485.929993  188.240005  461.089996   22139600  21910500  17380900
2025-12-31  487.839996  189.570007  456.100006   27293600  24383700  16377700

Price
Ticker          META      MSFT       NVDA       TSLA
Date
2021-01-04  15106100  37130100  560640000  145914600
2021-01-05   9871600  23823000  322760000   96735600
2021-01-06  24354100  35930700  580424000  134100000
2021-01-07  15789800  27694500  461480000  154496700
2021-01-08  18528300  22956200  292528000  225166500
...              ...       ...        ...        ...
2025-12-24   5627500   5855900   65528500   41285400
2025-12-26   7133800   8842200  139740300   58780700
2025-12-29   8506500  10893400  120006100   66263000
2025-12-30   9187500  13944500   97687300   59238500
2025-12-31   7940400  15601600  120100500   49078000

[1255 rows x 35 columns]

In [40]:
pd.DataFrame({
    'missing' : open_close_data.isna().sum()
}).sort_values('missing', ascending=False)

               missing
Price  Ticker
Close  AAPL          0
       AMZN          0
       GOOGL         0
       META          0
       MSFT          0
       NVDA          0
       TSLA          0
High   AAPL          0
       AMZN          0
       GOOGL         0
       META          0
       MSFT          0
       NVDA          0
       TSLA          0
Low    AAPL          0
       AMZN          0
       GOOGL         0
       META          0
       MSFT          0
       NVDA          0
       TSLA          0
Open   AAPL          0
       AMZN          0
       GOOGL         0
       META          0
       MSFT          0
       NVDA          0
       TSLA          0
Volume AAPL          0
       AMZN          0
       GOOGL         0
       META          0
       MSFT          0
       NVDA          0
       TSLA          0

There are no missing value in the data. However, pulling all 7 tickers info cause the data to contain too many columns. Reducing the dataset by grouping it by ticker may make future data processing much efficient.

In [46]:
#Get individual ticker open, close, low, high, volume data
appl_data = yf.download("AAPL", start_date, end_date).reset_index()
msft_data = yf.download("MSFT", start_date, end_date).reset_index()
googl_data = yf.download("GOOGL", start_date, end_date).reset_index()
amzn_data = yf.download("AMZN", start_date, end_date).reset_index()
meta_data = yf.download("META", start_date, end_date).reset_index()
nvda_data = yf.download("NVDA", start_date, end_date).reset_index()
tsla_data = yf.download("TSLA", start_date, end_date).reset_index()

#Save data into csv file for processing (keep index True to get date column)
appl_data.to_csv("appl.csv", index=True)
msft_data.to_csv("msft.csv", index=True)
googl_data.to_csv("googl.csv", index=True)
amzn_data.to_csv("amzn.csv", index=True)
meta_data.to_csv("meta.csv", index=True)
nvda_data.to_csv("nvda.csv", index=True)
tsla_data.to_csv("tsla.csv", index=True)

C:\Users\WEN YUAN\AppData\Local\Temp\ipykernel_2992\3859236872.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  appl_data = yf.download("AAPL", start_date, end_date).reset_index()
[*********************100%***********************]  1 of 1 completed
C:\Users\WEN YUAN\AppData\Local\Temp\ipykernel_2992\3859236872.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  msft_data = yf.download("MSFT", start_date, end_date).reset_index()
[*********************100%***********************]  1 of 1 completed
C:\Users\WEN YUAN\AppData\Local\Temp\ipykernel_2992\3859236872.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  googl_data = yf.download("GOOGL", start_date, end_date).reset_index()
[*********************100%***********************]  1 of 1 completed
C:\Users\WEN YUAN\AppData\Local\Temp\ipykernel_2992\3859236872.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  amzn_data = yf.download("AMZN", start_date, end_date).reset_index()
[*********************100%***********************]  1 of 1 completed
C:\Users\WEN YUAN\AppData\Local\Temp\ipykernel_2992\3859236872.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
  meta_data = yf.download("META", start_date, end_date).reset_index()
[*********************100%***********************]  1 of 1 completed
C:\Users\WEN YUAN\AppData\Local\Temp\ipykernel_2992\3859236872.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  nvda_data = yf.download("NVDA", start_date, end_date).reset_index()
[*********************100%***********************]  1 of 1 completed
C:\Users\WEN YUAN\AppData\Local\Temp\ipykernel_2992\3859236872.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  tsla_data = yf.download("TSLA", start_date, end_date).reset_index()
[*********************100%***********************]  1 of 1 completed

In [47]:
appl_data

Price        Date       Close        High         Low        Open     Volume
Ticker                   AAPL        AAPL        AAPL        AAPL       AAPL
0      2021-01-04  125.974457  130.062953  123.394807  129.975346  143301900
1      2021-01-05  127.531960  128.242590  125.020451  125.468246   97664900
2      2021-01-06  123.239052  127.570919  123.024891  124.329321  155088000
3      2021-01-07  127.444389  128.135547  124.465627  124.952354  109578200
4      2021-01-08  128.544388  129.108992  126.772697  128.914290  105158200
...           ...         ...         ...         ...         ...        ...
1250   2025-12-24  273.809998  275.429993  272.200012  272.339996   17910600
1251   2025-12-26  273.399994  275.369995  272.859985  274.160004   21521800
1252   2025-12-29  273.760010  274.359985  272.350006  272.690002   23715200
1253   2025-12-30  273.079987  274.079987  272.279999  272.809998   22139600
1254   2025-12-31  271.859985  273.679993  271.750000  273.059998   27293600

[1255 rows x 6 columns]

In [51]:
du1 = pd.DataFrame({
    'column': appl_data.columns,
    'role': ['identifier', 'target', 'feature', 'feature', 'feature', 'feature'],  # e.g., 'feature', 'target', 'identifier', 'metadata', 'ambiguous'
    'type': ['num-cont', 'num-cont', 'num-cont', 'num-cont', 'num-cont', 'num-cont'],  # e.g., 'num-cont', 'num-disc', 'cat-nom', 'cat-ord', 'bool'
})
du1

           column        role      type
0        (Date, )  identifier  num-cont
1   (Close, AAPL)      target  num-cont
2    (High, AAPL)     feature  num-cont
3     (Low, AAPL)     feature  num-cont
4    (Open, AAPL)     feature  num-cont
5  (Volume, AAPL)     feature  num-cont

For Single stock data, date can be an identifier that serves as an index to join with other data like interest rates or ETF indexes in the future. Since most machine learning algorithms cannot make use of date as a data type to generate insightful outcomes, date could be further broken down into columns to extract temporal features.

In [ ]:
# Data Preparation (they say cant do feature engineering, so prob dunnid do yet)
#TODO: Break the date down into different columns 
#day_of_week (catch Monday effect)
#month (catch seasonal trends)
#is_quarter_end (catch institutional rebalancing)